apiVersion: apps/v1
kind: Deployment
metadata:
  name: stock-be
  namespace: stock-app
  labels:
    app: stock-be
spec:
  replicas: 1
  template:
    metadata:
      name: stock-be
      labels:
        app: stock-be
    spec:
      nodeSelector:
        ram: high
      containers:
        - name: stock-be
          image: ghcr.io/whoant/stock-be:VERSION
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3000
          resources:
            limits:
              memory: "200Mi"
              cpu: "200m"
            requests:
              memory: "100Mi"
              cpu: "100m"
          envFrom:
            - secretRef:
                { name: secret.stock-be }
      restartPolicy: Always
  selector:
    matchLabels:
      app: stock-be
