version: '3.9'
services:
  stock-be:
    build:
      context: ./
    ports:
      - '3000:3000'
      - '9229:9229'
    volumes:
      - ./src:/opt/src
      - /opt/node_modules
    environment:
      - NODE_ENV=development
    command:
      - nodemon
      - -L
      - --inspect=0.0.0.0:9229
      - app.js
