apiVersion: v1
kind: Service
metadata:
  name: stock-be
  namespace: stock-app
spec:
  selector:
    app: stock-be
  ports:
    - port: 3001
      targetPort: 3000
      nodePort: 30014
  type: NodePort
